version: '3.3'

services:
  database:
    image: "postgres" # using latest official postgres version
    restart: always
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    logging:
        options:
            max-size: 10m
            max-file: "3"
    ports:
          - '5438:5432'
    volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env # configure postgres
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./dockerfile
    image: "mhmdrfq/backend-image"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    image: "mhmdrfq/frontend-image"
    ports:
      - "8081:8081"
    